runtime: go
api_version: go1.8

env_variables:

nobuild_files:

skip_files:

service: default

handlers:

- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /_ah/.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always
